const categories=[{id:'all',name:'全部',icon:'◉'},{id:'protein',name:'蛋白质',icon:'🥚'},{id:'veg',name:'蔬菜',icon:'🥬'},{id:'carb',name:'主食',icon:'🍚'},{id:'seasoning',name:'调味',icon:'🫙'}];
const ingredients=[
 {id:'chicken',name:'鸡胸肉',emoji:'🍗',cat:'protein'},{id:'salmon',name:'三文鱼',emoji:'🐟',cat:'protein'},{id:'egg',name:'鸡蛋',emoji:'🥚',cat:'protein'},{id:'tofu',name:'豆腐',emoji:'◻️',cat:'protein'},{id:'shrimp',name:'鲜虾',emoji:'🦐',cat:'protein'},{id:'beef',name:'瘦牛肉',emoji:'🥩',cat:'protein'},
 {id:'broccoli',name:'西兰花',emoji:'🥦',cat:'veg'},{id:'tomato',name:'番茄',emoji:'🍅',cat:'veg'},{id:'mushroom',name:'蘑菇',emoji:'🍄',cat:'veg'},{id:'spinach',name:'菠菜',emoji:'🥬',cat:'veg'},{id:'avocado',name:'牛油果',emoji:'🥑',cat:'veg'},{id:'pepper',name:'彩椒',emoji:'🫑',cat:'veg'},{id:'cucumber',name:'黄瓜',emoji:'🥒',cat:'veg'},{id:'corn',name:'玉米',emoji:'🌽',cat:'veg'},
 {id:'rice',name:'糙米饭',emoji:'🍚',cat:'carb'},{id:'noodle',name:'荞麦面',emoji:'🍜',cat:'carb'},{id:'potato',name:'红薯',emoji:'🍠',cat:'carb'},{id:'quinoa',name:'藜麦',emoji:'🌾',cat:'carb'},
 {id:'lemon',name:'柠檬',emoji:'🍋',cat:'seasoning'},{id:'chili',name:'辣椒',emoji:'🌶️',cat:'seasoning'},{id:'garlic',name:'大蒜',emoji:'🧄',cat:'seasoning'},{id:'sesame',name:'芝麻',emoji:'⚪',cat:'seasoning'},{id:'basil',name:'罗勒',emoji:'🌿',cat:'seasoning'},{id:'yogurt',name:'希腊酸奶',emoji:'🥣',cat:'seasoning'}
];
const recipes=[
 {id:1,name:'柠香三文鱼藜麦碗',cuisine:'地中海',icon:'🥗',color:'#bdd7b7',needs:['salmon','quinoa','cucumber','tomato','lemon'],time:25,cal:486,protein:36,carb:42,desc:'清亮柠香裹住煎香三文鱼，搭配松软藜麦与爽脆蔬菜。',steps:['藜麦洗净后煮 15 分钟，沥干放凉。','三文鱼用盐、黑胡椒和柠檬汁腌 5 分钟，两面煎熟。','黄瓜与番茄切块，和藜麦拌匀，放上三文鱼即可。']},
 {id:2,name:'照烧鸡肉糙米饭',cuisine:'日式',icon:'🍱',color:'#e4cfa3',needs:['chicken','rice','broccoli','mushroom','sesame'],time:20,cal:521,protein:42,carb:57,desc:'少糖照烧汁的醇厚鲜甜，配一碗高纤糙米饭。',steps:['鸡胸肉切块，用少量酱油、蜂蜜与姜末腌制。','热锅煎熟鸡肉，加入蘑菇翻炒收汁。','糙米饭装碗，配焯熟西兰花，撒芝麻。']},
 {id:3,name:'麻辣豆腐荞麦面',cuisine:'中式',icon:'🍜',color:'#e7a482',needs:['tofu','noodle','spinach','chili','garlic'],time:15,cal:438,protein:24,carb:55,desc:'温和麻辣唤醒味蕾，豆腐和荞麦面带来扎实饱腹感。',steps:['豆腐切块煎至表面微黄。','蒜末与辣椒炒香，加少量酱油和水煮成汤底。','荞麦面煮熟，加入菠菜和豆腐，煮开即可。']},
 {id:4,name:'牛油果鲜虾塔可碗',cuisine:'墨西哥',icon:'🌮',color:'#ebc86c',needs:['shrimp','avocado','corn','tomato','rice','lemon'],time:18,cal:472,protein:31,carb:51,desc:'不需要饼皮的轻盈塔可碗，酸、香、甜、辣层次丰富。',steps:['鲜虾用孜然和辣椒粉煎熟。','玉米、番茄、牛油果切块，挤入柠檬汁。','糙米饭打底，码上蔬菜和虾仁。']},
 {id:5,name:'罗勒番茄鸡肉意面',cuisine:'意式',icon:'🍝',color:'#d79d78',needs:['chicken','noodle','tomato','mushroom','basil','garlic'],time:25,cal:509,protein:39,carb:58,desc:'新鲜番茄做成的清爽酱汁，让家常鸡肉也有南欧气息。',steps:['荞麦面煮至适口，保留半杯面汤。','鸡肉煎熟，加入蒜末、番茄和蘑菇炒软。','加入面条与少量面汤翻拌，最后放罗勒。']},
 {id:6,name:'泰式酸辣牛肉沙拉',cuisine:'东南亚',icon:'🥙',color:'#acd0a1',needs:['beef','cucumber','pepper','lemon','chili','garlic'],time:20,cal:395,protein:35,carb:24,desc:'酸辣开胃、蔬菜占比丰富，适合清爽又满足的一餐。',steps:['牛肉大火快煎至喜欢的熟度，静置后切片。','黄瓜和彩椒切丝，蒜、辣椒、柠檬汁调成汁。','牛肉与蔬菜拌匀，静置 2 分钟入味。']},
 {id:7,name:'菌菇豆腐韩式拌饭',cuisine:'韩式',icon:'🍲',color:'#d8b28e',needs:['tofu','rice','mushroom','spinach','egg','sesame'],time:25,cal:465,protein:26,carb:56,desc:'多种食材一碗集合，用少量韩式辣酱带出满足风味。',steps:['蘑菇、菠菜和豆腐分别少油煎炒。','糙米饭装碗，依次摆好配菜。','煎一个太阳蛋，放在中央，撒芝麻拌匀。']},
 {id:8,name:'彩椒鸡蛋中式炒饭',cuisine:'中式',icon:'🍳',color:'#e9c883',needs:['egg','rice','pepper','corn','spinach','garlic'],time:15,cal:442,protein:22,carb:61,desc:'用隔夜糙米和大量蔬菜，做一份粒粒分明的轻负担炒饭。',steps:['鸡蛋炒散盛出。','少油炒香蒜末，加入彩椒、玉米和菠菜。','倒入糙米饭与鸡蛋，大火翻炒，少量酱油调味。']},
 {id:9,name:'酸奶香草鸡肉卷碗',cuisine:'地中海',icon:'🫓',color:'#c9d8b2',needs:['chicken','yogurt','cucumber','tomato','quinoa','lemon'],time:22,cal:455,protein:43,carb:39,desc:'酸奶香草酱替代高脂沙拉酱，清新柔滑又高蛋白。',steps:['鸡肉用柠檬、香草与黑胡椒腌制后煎熟。','酸奶加入黄瓜碎、柠檬汁和少量盐调匀。','藜麦打底，配番茄、鸡肉，淋酸奶酱。']}
];
let state={cat:'all',selected:new Set(),cuisine:'全部',saved:new Set(JSON.parse(localStorage.getItem('shiwei-saved')||'[]')),matched:false};
const $=s=>document.querySelector(s); const byId=id=>ingredients.find(x=>x.id===id);
function renderCategories(){ $('#categoryTabs').innerHTML=categories.map(c=>`<button class="category-tab ${state.cat===c.id?'active':''}" data-cat="${c.id}"><span>${c.icon}</span>${c.name}</button>`).join(''); }
function renderIngredients(){ const q=$('#ingredientSearch').value.trim(); const list=ingredients.filter(i=>(state.cat==='all'||i.cat===state.cat)&&i.name.includes(q)); $('#ingredientGrid').innerHTML=list.map(i=>`<button class="ingredient ${state.selected.has(i.id)?'selected':''}" data-id="${i.id}"><span class="check">✓</span><span class="emoji">${i.emoji}</span><span>${i.name}</span></button>`).join('')||'<p>没有找到相关食材</p>'; }
function renderSelection(){ const arr=[...state.selected]; $('#selectedCount').textContent=arr.length; $('#selectedTags').innerHTML=arr.length?arr.map(id=>`<button data-remove="${id}">${byId(id).name} ×</button>`).join(''):'<p class="empty-hint">还没有选择食材</p>'; $('#matchBtn').disabled=arr.length<2; const veg=arr.filter(id=>byId(id).cat==='veg').length,pro=arr.filter(id=>byId(id).cat==='protein').length; $('#nutritionHint').textContent=veg>=2?'高纤 · 多蔬菜 · 清爽':pro>=2?'高蛋白 · 饱腹 · 均衡':'均衡 · 清爽 · 高纤'; }
function scoredRecipes(){ return recipes.map(r=>{const have=r.needs.filter(x=>state.selected.has(x));return {...r,score:have.length,percent:Math.round(have.length/r.needs.length*100),missing:r.needs.filter(x=>!state.selected.has(x))}}).sort((a,b)=>b.score-a.score); }
function renderCuisines(){ const list=['全部',...new Set(recipes.map(r=>r.cuisine))]; $('#cuisineFilter').innerHTML=list.map(c=>`<button class="${state.cuisine===c?'active':''}" data-cuisine="${c}">${c}</button>`).join(''); }
function renderRecipes(){ let list=scoredRecipes().filter(r=>state.cuisine==='全部'||r.cuisine===state.cuisine); if(state.matched&&state.selected.size) list=list.filter(r=>r.score>0); $('#recipeGrid').innerHTML=list.length?list.map(r=>`<article class="recipe-card" data-open="${r.id}"><div class="recipe-art" style="background:${r.color}"><span class="recipe-icon">${r.icon}</span><span class="match-badge">${state.selected.size?r.percent+'% 匹配':'今日推荐'}</span></div><button class="save-card ${state.saved.has(r.id)?'saved':''}" data-save="${r.id}" aria-label="收藏">${state.saved.has(r.id)?'♥':'♡'}</button><div class="recipe-body"><span class="recipe-meta">${r.cuisine} · ${r.time} 分钟</span><h3>${r.name}</h3><p class="recipe-desc">${r.desc}</p><div class="nutrition-row"><span><strong>${r.cal}</strong>千卡</span><span><strong>${r.protein}g</strong>蛋白质</span><span><strong>${r.carb}g</strong>碳水</span></div>${state.selected.size?`<p class="missing">${r.missing.length?'还缺：'+r.missing.map(x=>byId(x).name).join('、'):'✓ 食材已经齐全'}</p>`:''}</div></article>`).join(''):'<div class="empty-result">这个组合暂时没有匹配菜谱，试试增加一种蛋白质或主食吧。</div>'; $('#savedCount').textContent=state.saved.size; }
function openRecipe(id){const r=recipes.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-hero" style="background:${r.color}"><span class="recipe-icon">${r.icon}</span><div><span class="recipe-meta">${r.cuisine} · ${r.time} 分钟</span><h2>${r.name}</h2><p>${r.desc}</p></div></div><div class="modal-body"><div class="modal-body-grid"><div><h3>所需食材</h3><ul>${r.needs.map(x=>`<li>${byId(x).name}${state.selected.has(x)?' ✓':''}</li>`).join('')}</ul></div><div><h3>简单做法</h3><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol></div></div></div>`;$('#recipeModal').showModal();}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
document.addEventListener('click',e=>{const cat=e.target.closest('[data-cat]');if(cat){state.cat=cat.dataset.cat;renderCategories();renderIngredients()}const ing=e.target.closest('[data-id]');if(ing){state.selected.has(ing.dataset.id)?state.selected.delete(ing.dataset.id):state.selected.add(ing.dataset.id);renderIngredients();renderSelection()}const rem=e.target.closest('[data-remove]');if(rem){state.selected.delete(rem.dataset.remove);renderIngredients();renderSelection()}const cuisine=e.target.closest('[data-cuisine]');if(cuisine){state.cuisine=cuisine.dataset.cuisine;renderCuisines();renderRecipes()}const save=e.target.closest('[data-save]');if(save){e.stopPropagation();const id=+save.dataset.save;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);localStorage.setItem('shiwei-saved',JSON.stringify([...state.saved]));renderRecipes();toast(state.saved.has(id)?'已收藏这道菜':'已取消收藏')}const card=e.target.closest('[data-open]');if(card&&!save)openRecipe(+card.dataset.open)});
$('#ingredientSearch').addEventListener('input',renderIngredients);$('#clearBtn').onclick=()=>{state.selected.clear();renderIngredients();renderSelection()};$('#matchBtn').onclick=()=>{state.matched=true;renderRecipes();$('#resultSummary').textContent=`根据你选择的 ${state.selected.size} 种食材，已按匹配度排序。`;$('#recipes').scrollIntoView();toast('搭配完成，看看你的专属菜单')};$('#modalClose').onclick=()=>$('#recipeModal').close();$('#recipeModal').addEventListener('click',e=>{if(e.target===$('#recipeModal'))$('#recipeModal').close()});$('#savedBtn').onclick=()=>{state.matched=false;state.cuisine='全部';renderCuisines();const all=scoredRecipes();$('#recipeGrid').innerHTML='';renderRecipes();$('#recipes').scrollIntoView();toast(state.saved.size?`你收藏了 ${state.saved.size} 道菜`:'还没有收藏菜谱')};
renderCategories();renderIngredients();renderSelection();renderCuisines();renderRecipes();
