Exit code: 0
Wall time: 9.2 seconds
Output:
const categories=[{id:'all',name:'鍏ㄩ儴',icon:'鈼?},{id:'protein',name:'铔嬬櫧璐?,icon:'馃'},{id:'veg',name:'钄彍',icon:'馃ガ'},{id:'carb',name:'涓婚',icon:'馃崥'},{id:'seasoning',name:'璋冨懗',icon:'馃珯'}];
const ingredients=[
 {id:'chicken',name:'楦¤兏鑲?,emoji:'馃崡',cat:'protein'},{id:'salmon',name:'涓夋枃楸?,emoji:'馃悷',cat:'protein'},{id:'egg',name:'楦¤泲',emoji:'馃',cat:'protein'},{id:'tofu',name:'璞嗚厫',emoji:'鈼伙笍',cat:'protein'},{id:'shrimp',name:'椴滆櫨',emoji:'馃',cat:'protein'},{id:'beef',name:'鐦︾墰鑲?,emoji:'馃ォ',cat:'protein'},
 {id:'broccoli',name:'瑗垮叞鑺?,emoji:'馃ウ',cat:'veg'},{id:'tomato',name:'鐣寗',emoji:'馃崊',cat:'veg'},{id:'mushroom',name:'铇戣弴',emoji:'馃崉',cat:'veg'},{id:'spinach',name:'鑿犺彍',emoji:'馃ガ',cat:'veg'},{id:'avocado',name:'鐗涙补鏋?,emoji:'馃',cat:'veg'},{id:'pepper',name:'褰╂',emoji:'馃珣',cat:'veg'},{id:'cucumber',name:'榛勭摐',emoji:'馃',cat:'veg'},{id:'corn',name:'鐜夌背',emoji:'馃尳',cat:'veg'},
 {id:'rice',name:'绯欑背楗?,emoji:'馃崥',cat:'carb'},{id:'noodle',name:'鑽為害闈?,emoji:'馃崪',cat:'carb'},{id:'potato',name:'绾㈣柉',emoji:'馃崰',cat:'carb'},{id:'quinoa',name:'钘滈害',emoji:'馃尵',cat:'carb'},
 {id:'lemon',name:'鏌犳',emoji:'馃崑',cat:'seasoning'},{id:'chili',name:'杈ｆ',emoji:'馃尪锔?,cat:'seasoning'},{id:'garlic',name:'澶ц挏',emoji:'馃',cat:'seasoning'},{id:'sesame',name:'鑺濋夯',emoji:'鈿?,cat:'seasoning'},{id:'basil',name:'缃楀嫆',emoji:'馃尶',cat:'seasoning'},{id:'yogurt',name:'甯岃厞閰稿ザ',emoji:'馃ィ',cat:'seasoning'}
];
const recipes=[
 {id:1,name:'鏌犻涓夋枃楸艰棞楹︾',cuisine:'鍦颁腑娴?,icon:'馃',color:'#bdd7b7',needs:['salmon','quinoa','cucumber','tomato','lemon'],time:25,cal:486,protein:36,carb:42,desc:'娓呬寒鏌犻瑁逛綇鐓庨涓夋枃楸硷紝鎼厤鏉捐蒋钘滈害涓庣埥鑴嗚敩鑿溿€?,steps:['钘滈害娲楀噣鍚庣叜 15 鍒嗛挓锛屾播骞叉斁鍑夈€?,'涓夋枃楸肩敤鐩愩€侀粦鑳℃鍜屾煚妾眮鑵?5 鍒嗛挓锛屼袱闈㈢厧鐔熴€?,'榛勭摐涓庣暘鑼勫垏鍧楋紝鍜岃棞楹︽媽鍖€锛屾斁涓婁笁鏂囬奔鍗冲彲銆?]},
 {id:2,name:'鐓х儳楦¤倝绯欑背楗?,cuisine:'鏃ュ紡',icon:'馃嵄',color:'#e4cfa3',needs:['chicken','rice','broccoli','mushroom','sesame'],time:20,cal:521,protein:42,carb:57,desc:'灏戠硸鐓х儳姹佺殑閱囧帤椴滅敎锛岄厤涓€纰楅珮绾ょ硻绫抽キ銆?,steps:['楦¤兏鑲夊垏鍧楋紝鐢ㄥ皯閲忛叡娌广€佽渹铚滀笌濮滄湯鑵屽埗銆?,'鐑攨鐓庣啛楦¤倝锛屽姞鍏ヨ槕鑿囩炕鐐掓敹姹併€?,'绯欑背楗纰楋紝閰嶇劘鐔熻タ鍏拌姳锛屾拻鑺濋夯銆?]},
 {id:3,name:'楹昏荆璞嗚厫鑽為害闈?,cuisine:'涓紡',icon:'馃崪',color:'#e7a482',needs:['tofu','noodle','spinach','chili','garlic'],time:15,cal:438,protein:24,carb:55,desc:'娓╁拰楹昏荆鍞ら啋鍛宠暰锛岃眴鑵愬拰鑽為害闈㈠甫鏉ユ墡瀹為ケ鑵规劅銆?,steps:['璞嗚厫鍒囧潡鐓庤嚦琛ㄩ潰寰粍銆?,'钂滄湯涓庤荆妞掔倰棣欙紝鍔犲皯閲忛叡娌瑰拰姘寸叜鎴愭堡搴曘€?,'鑽為害闈㈢叜鐔燂紝鍔犲叆鑿犺彍鍜岃眴鑵愶紝鐓紑鍗冲彲銆?]},
 {id:4,name:'鐗涙补鏋滈矞铏惧鍙',cuisine:'澧ㄨタ鍝?,icon:'馃尞',color:'#ebc86c',needs:['shrimp','avocado','corn','tomato','rice','lemon'],time:18,cal:472,protein:31,carb:51,desc:'涓嶉渶瑕侀ゼ鐨殑杞荤泩濉斿彲纰楋紝閰搞€侀銆佺敎銆佽荆灞傛涓板瘜銆?,steps:['椴滆櫨鐢ㄥ瓬鐒跺拰杈ｆ绮夌厧鐔熴€?,'鐜夌背銆佺暘鑼勩€佺墰娌规灉鍒囧潡锛屾尋鍏ユ煚妾眮銆?,'绯欑背楗墦搴曪紝鐮佷笂钄彍鍜岃櫨浠併€?]},
 {id:5,name:'缃楀嫆鐣寗楦¤倝鎰忛潰',cuisine:'鎰忓紡',icon:'馃崫',color:'#d79d78',needs:['chicken','noodle','tomato','mushroom','basil','garlic'],time:25,cal:509,protein:39,carb:58,desc:'鏂伴矞鐣寗鍋氭垚鐨勬竻鐖介叡姹侊紝璁╁甯搁浮鑲変篃鏈夊崡娆ф皵鎭€?,steps:['鑽為害闈㈢叜鑷抽€傚彛锛屼繚鐣欏崐鏉潰姹ゃ€?,'楦¤倝鐓庣啛锛屽姞鍏ヨ挏鏈€佺暘鑼勫拰铇戣弴鐐掕蒋銆?,'鍔犲叆闈㈡潯涓庡皯閲忛潰姹ょ炕鎷岋紝鏈€鍚庢斁缃楀嫆銆?]},
 {id:6,name:'娉板紡閰歌荆鐗涜倝娌欐媺',cuisine:'涓滃崡浜?,icon:'馃',color:'#acd0a1',needs:['beef','cucumber','pepper','lemon','chili','garlic'],time:20,cal:395,protein:35,carb:24,desc:'閰歌荆寮€鑳冦€佽敩鑿滃崰姣斾赴瀵岋紝閫傚悎娓呯埥鍙堟弧瓒崇殑涓€椁愩€?,steps:['鐗涜倝澶х伀蹇厧鑷冲枩娆㈢殑鐔熷害锛岄潤缃悗鍒囩墖銆?,'榛勭摐鍜屽僵妞掑垏涓濓紝钂溿€佽荆妞掋€佹煚妾眮璋冩垚姹併€?,'鐗涜倝涓庤敩鑿滄媽鍖€锛岄潤缃?2 鍒嗛挓鍏ュ懗銆?]},
 {id:7,name:'鑿岃弴璞嗚厫闊╁紡鎷岄キ',cuisine:'闊╁紡',icon:'馃嵅',color:'#d8b28e',needs:['tofu','rice','mushroom','spinach','egg','sesame'],time:25,cal:465,protein:26,carb:56,desc:'澶氱椋熸潗涓€纰楅泦鍚堬紝鐢ㄥ皯閲忛煩寮忚荆閰卞甫鍑烘弧瓒抽鍛炽€?,steps:['铇戣弴銆佽彔鑿滃拰璞嗚厫鍒嗗埆灏戞补鐓庣倰銆?,'绯欑背楗纰楋紝渚濇鎽嗗ソ閰嶈彍銆?,'鐓庝竴涓お闃宠泲锛屾斁鍦ㄤ腑澶紝鎾掕姖楹绘媽鍖€銆?]},
 {id:8,name:'褰╂楦¤泲涓紡鐐掗キ',cuisine:'涓紡',icon:'馃嵆',color:'#e9c883',needs:['egg','rice','pepper','corn','spinach','garlic'],time:15,cal:442,protein:22,carb:61,desc:'鐢ㄩ殧澶滅硻绫冲拰澶ч噺钄彍锛屽仛涓€浠界矑绮掑垎鏄庣殑杞昏礋鎷呯倰楗€?,steps:['楦¤泲鐐掓暎鐩涘嚭銆?,'灏戞补鐐掗钂滄湯锛屽姞鍏ュ僵妞掋€佺帀绫冲拰鑿犺彍銆?,'鍊掑叆绯欑背楗笌楦¤泲锛屽ぇ鐏炕鐐掞紝灏戦噺閰辨补璋冨懗銆?]},
 {id:9,name:'閰稿ザ棣欒崏楦¤倝鍗风',cuisine:'鍦颁腑娴?,icon:'馃珦',color:'#c9d8b2',needs:['chicken','yogurt','cucumber','tomato','quinoa','lemon'],time:22,cal:455,protein:43,carb:39,desc:'閰稿ザ棣欒崏閰辨浛浠ｉ珮鑴傛矙鎷夐叡锛屾竻鏂版煍婊戝張楂樿泲鐧姐€?,steps:['楦¤倝鐢ㄦ煚妾€侀鑽変笌榛戣儭妞掕厡鍒跺悗鐓庣啛銆?,'閰稿ザ鍔犲叆榛勭摐纰庛€佹煚妾眮鍜屽皯閲忕洂璋冨寑銆?,'钘滈害鎵撳簳锛岄厤鐣寗銆侀浮鑲夛紝娣嬮吀濂堕叡銆?]}
];
let state={cat:'all',selected:new Set(),cuisine:'鍏ㄩ儴',saved:new Set(JSON.parse(localStorage.getItem('shiwei-saved')||'[]')),matched:false};
const $=s=>document.querySelector(s); const byId=id=>ingredients.find(x=>x.id===id);
function renderCategories(){ $('#categoryTabs').innerHTML=categories.map(c=>`<button class="category-tab ${state.cat===c.id?'active':''}" data-cat="${c.id}"><span>${c.icon}</span>${c.name}</button>`).join(''); }
function renderIngredients(){ const q=$('#ingredientSearch').value.trim(); const list=ingredients.filter(i=>(state.cat==='all'||i.cat===state.cat)&&i.name.includes(q)); $('#ingredientGrid').innerHTML=list.map(i=>`<button class="ingredient ${state.selected.has(i.id)?'selected':''}" data-id="${i.id}"><span class="check">鉁?/span><span class="emoji">${i.emoji}</span><span>${i.name}</span></button>`).join('')||'<p>娌℃湁鎵惧埌鐩稿叧椋熸潗</p>'; }
function renderSelection(){ const arr=[...state.selected]; $('#selectedCount').textContent=arr.length; $('#selectedTags').innerHTML=arr.length?arr.map(id=>`<button data-remove="${id}">${byId(id).name} 脳</button>`).join(''):'<p class="empty-hint">杩樻病鏈夐€夋嫨椋熸潗</p>'; $('#matchBtn').disabled=arr.length<2; const veg=arr.filter(id=>byId(id).cat==='veg').length,pro=arr.filter(id=>byId(id).cat==='protein').length; $('#nutritionHint').textContent=veg>=2?'楂樼氦 路 澶氳敩鑿?路 娓呯埥':pro>=2?'楂樿泲鐧?路 楗辫吂 路 鍧囪　':'鍧囪　 路 娓呯埥 路 楂樼氦'; }
function scoredRecipes(){ return recipes.map(r=>{const have=r.needs.filter(x=>state.selected.has(x));return {...r,score:have.length,percent:Math.round(have.length/r.needs.length*100),missing:r.needs.filter(x=>!state.selected.has(x))}}).sort((a,b)=>b.score-a.score); }
function renderCuisines(){ const list=['鍏ㄩ儴',...new Set(recipes.map(r=>r.cuisine))]; $('#cuisineFilter').innerHTML=list.map(c=>`<button class="${state.cuisine===c?'active':''}" data-cuisine="${c}">${c}</button>`).join(''); }
function renderRecipes(){ let list=scoredRecipes().filter(r=>state.cuisine==='鍏ㄩ儴'||r.cuisine===state.cuisine); if(state.matched&&state.selected.size) list=list.filter(r=>r.score>0); $('#recipeGrid').innerHTML=list.length?list.map(r=>`<article class="recipe-card" data-open="${r.id}"><div class="recipe-art" style="background:${r.color}"><span class="recipe-icon">${r.icon}</span><span class="match-badge">${state.selected.size?r.percent+'% 鍖归厤':'浠婃棩鎺ㄨ崘'}</span></div><button class="save-card ${state.saved.has(r.id)?'saved':''}" data-save="${r.id}" aria-label="鏀惰棌">${state.saved.has(r.id)?'鈾?:'鈾?}</button><div class="recipe-body"><span class="recipe-meta">${r.cuisine} 路 ${r.time} 鍒嗛挓</span><h3>${r.name}</h3><p class="recipe-desc">${r.desc}</p><div class="nutrition-row"><span><strong>${r.cal}</strong>鍗冨崱</span><span><strong>${r.protein}g</strong>铔嬬櫧璐?/span><span><strong>${r.carb}g</strong>纰虫按</span></div>${state.selected.size?`<p class="missing">${r.missing.length?'杩樼己锛?+r.missing.map(x=>byId(x).name).join('銆?):'鉁?椋熸潗宸茬粡榻愬叏'}</p>`:''}</div></article>`).join(''):'<div class="empty-result">杩欎釜缁勫悎鏆傛椂娌℃湁鍖归厤鑿滆氨锛岃瘯璇曞鍔犱竴绉嶈泲鐧借川鎴栦富椋熷惂銆?/div>'; $('#savedCount').textContent=state.saved.size; }
function openRecipe(id){const r=recipes.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-hero" style="background:${r.color}"><span class="recipe-icon">${r.icon}</span><div><span class="recipe-meta">${r.cuisine} 路 ${r.time} 鍒嗛挓</span><h2>${r.name}</h2><p>${r.desc}</p></div></div><div class="modal-body"><div class="modal-body-grid"><div><h3>鎵€闇€椋熸潗</h3><ul>${r.needs.map(x=>`<li>${byId(x).name}${state.selected.has(x)?' 鉁?:''}</li>`).join('')}</ul></div><div><h3>绠€鍗曞仛娉?/h3><ol>${r.steps.map(x=>`<li>${x}</li>`).join('')}</ol></div></div></div>`;$('#recipeModal').showModal();}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
document.addEventListener('click',e=>{const cat=e.target.closest('[data-cat]');if(cat){state.cat=cat.dataset.cat;renderCategories();renderIngredients()}const ing=e.target.closest('[data-id]');if(ing){state.selected.has(ing.dataset.id)?state.selected.delete(ing.dataset.id):state.selected.add(ing.dataset.id);renderIngredients();renderSelection()}const rem=e.target.closest('[data-remove]');if(rem){state.selected.delete(rem.dataset.remove);renderIngredients();renderSelection()}const cuisine=e.target.closest('[data-cuisine]');if(cuisine){state.cuisine=cuisine.dataset.cuisine;renderCuisines();renderRecipes()}const save=e.target.closest('[data-save]');if(save){e.stopPropagation();const id=+save.dataset.save;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);localStorage.setItem('shiwei-saved',JSON.stringify([...state.saved]));renderRecipes();toast(state.saved.has(id)?'宸叉敹钘忚繖閬撹彍':'宸插彇娑堟敹钘?)}const card=e.target.closest('[data-open]');if(card&&!save)openRecipe(+card.dataset.open)});
$('#ingredientSearch').addEventListener('input',renderIngredients);$('#clearBtn').onclick=()=>{state.selected.clear();renderIngredients();renderSelection()};$('#matchBtn').onclick=()=>{state.matched=true;renderRecipes();$('#resultSummary').textContent=`鏍规嵁浣犻€夋嫨鐨?${state.selected.size} 绉嶉鏉愶紝宸叉寜鍖归厤搴︽帓搴忋€俙;$('#recipes').scrollIntoView();toast('鎼厤瀹屾垚锛岀湅鐪嬩綘鐨勪笓灞炶彍鍗?)};$('#modalClose').onclick=()=>$('#recipeModal').close();$('#recipeModal').addEventListener('click',e=>{if(e.target===$('#recipeModal'))$('#recipeModal').close()});$('#savedBtn').onclick=()=>{state.matched=false;state.cuisine='鍏ㄩ儴';renderCuisines();const all=scoredRecipes();$('#recipeGrid').innerHTML='';renderRecipes();$('#recipes').scrollIntoView();toast(state.saved.size?`浣犳敹钘忎簡 ${state.saved.size} 閬撹彍`:'杩樻病鏈夋敹钘忚彍璋?)};
renderCategories();renderIngredients();renderSelection();renderCuisines();renderRecipes();

